# Imports

In [ ]:
! pip install pymongo
import pymongo
from pymongo import UpdateOne
import pandas as pd

from google.colab import userdata
from bson.dbref import DBRef

from sklearn.model_selection import GridSearchCV

Collecting pymongo
  Downloading pymongo-4.11.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Downloading pymongo-4.11.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 15.0 MB/s eta 0:00:00
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.6/313.6 kB 17.8 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.7.0 pymongo-4.11.3

# Connecting to MongoDB

In [ ]:
client = pymongo.MongoClient(userdata.get('MONGO_CONN_STR'), connectTimeoutMS=6000000)

try:
  client.admin.command('ping')
  print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
  print('Failed to connect: ' + e)

Pinged your deployment. You successfully connected to MongoDB!

## Setting up database

In [ ]:
db = client['spotifyDatabase']

tracks = db['tracks']
genres = db['genres']
artists = db['artists']

Data aquisition

In [ ]:
df = pd.read_csv("hf://datasets/maharshipandya/spotify-tracks-dataset/dataset.csv")

df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

Data cleaning

In [ ]:
initial_rows = len(df)
df = df.dropna() # drop row with nan values
rows_removed = initial_rows - len(df)
print(f"{rows_removed} rows removed.")

if 'Unnamed: 0' in df.columns: #drop unnamed/empty column
  df = df.drop(columns=['Unnamed: 0'])
  print("Unnamed column removed successfully.")
else:
  print("No unnamed column found in the DataFrame.")

1 rows removed.
Unnamed column removed successfully.

Creating dataframe of individual artists

In [ ]:

artists_df = df['artists'].str.split(';').explode().reset_index(drop=True)

# Remove duplicates and convert to DataFrame
artists_df = pd.DataFrame(artists_df.unique(), columns=['artist'])

# Display the resulting DataFrame
artists_df

                                     artist
0                               Gen Hoshino
1                              Ben Woodward
2                         Ingrid Michaelson
3                                      ZAYN
4                              Kina Grannis
...                                     ...
29854             The WRLDFMS Tony Williams
29855                            John Wilds
29856                          Molly Skaggs
29857  Cuencos Tibetanos Sonidos Relajantes
29858                           Brock Human

[29859 rows x 1 columns]

# Database injection

- insert artists and map their id to their string name
- insert genres and map their id to their string name
- parse artists from tracks and replace their strings with id references
- same thing for genres
- insert the tracks to the database

In [ ]:
# Create a dictionary to map artist names to their corresponding MongoDB IDs


# Extract unique artist names
artist_names = df['artists'].str.split(';').explode().unique()

# Create a list of artist documents for bulk insertion
artist_docs = [{'artist': artist_name} for artist_name in artist_names]

# Use the 'unordered' bulk write operation for better performance
try:
    result = artists.insert_many(artist_docs, ordered=False)
    print(f"Inserted {len(result.inserted_ids)} artists.")
except pymongo.errors.BulkWriteError as bwe:
    # Handle duplicate key errors (if any) during bulk insert
    print(bwe.details)

# Create a dictionary to map artist names to their corresponding MongoDB IDs
artist_name_to_id = {doc['artist']: doc['_id'] for doc in artists.find({}, {'artist': 1, '_id': 1})}

genres_df = df['track_genre'].unique()
genre_name_to_id = {}

for genre_name in genres_df:
    if genre_name not in genre_name_to_id:
      result = genres.insert_one({'genre': genre_name})
      genre_name_to_id[genre_name] = result.inserted_id

# Preprocess the DataFrame
def preprocess_data(row):
    artist_refs = []
    for artist_name in row['artists'].split(';'):
      if artist_name in artist_name_to_id:
        artist_refs.append(DBRef('artists', artist_name_to_id[artist_name]))
      else:
        # Handle cases where artist is not found
        print(f"Warning: Artist '{artist_name}' not found in the database.")

    genre_ref = DBRef('genres', genre_name_to_id[row['track_genre']])
    if genre_ref is None:
        print(f"Warning: Genre '{row['track_genre']}' not found in the database.")

    track_data = {
        'track_id': row['track_id'],
        'artists': artist_refs,
        'track_genre': genre_ref,
    }

    for column in df.columns:
        if column not in ['track_id', 'artists', 'track_genre']:
            track_data[column] = row[column]

    return track_data

preprocessed_data = df.apply(preprocess_data, axis=1).to_list()

# Insert the preprocessed data into the 'tracks' collection

for i in range(0, len(preprocessed_data), 1000):
  batch = preprocessed_data[i:i+1000]
  tracks.insert_many(batch)
  print(f"Inserted {len(batch)} tracks. Progress: {i}/{len(preprocessed_data)}")

# Prepare bulk write operations for artists
artist_update_operations = []
for track in preprocessed_data:
    for artist_ref in track['artists']:
        artist_update_operations.append(
            UpdateOne({'_id': artist_ref.id}, {'$push': {'tracks': DBRef('tracks', track['track_id'])}})
        )

# Execute bulk write for artists
if artist_update_operations:
    artists.bulk_write(artist_update_operations, ordered=False)

# Prepare bulk write operations for genres
genre_update_operations = []
for track in preprocessed_data:
    genre_update_operations.append(
        UpdateOne({'_id': track['track_genre'].id}, {'$push': {'tracks': DBRef('tracks', track['track_id'])}})
    )

# Execute bulk write for genres
if genre_update_operations:
    genres.bulk_write(genre_update_operations, ordered=False)

Inserted 29859 artists.
Inserted 1000 tracks. Progress: 0/113999
Inserted 1000 tracks. Progress: 1000/113999
Inserted 1000 tracks. Progress: 2000/113999
Inserted 1000 tracks. Progress: 3000/113999
Inserted 1000 tracks. Progress: 4000/113999
Inserted 1000 tracks. Progress: 5000/113999
Inserted 1000 tracks. Progress: 6000/113999
Inserted 1000 tracks. Progress: 7000/113999
Inserted 1000 tracks. Progress: 8000/113999
Inserted 1000 tracks. Progress: 9000/113999
Inserted 1000 tracks. Progress: 10000/113999
Inserted 1000 tracks. Progress: 11000/113999
Inserted 1000 tracks. Progress: 12000/113999
Inserted 1000 tracks. Progress: 13000/113999
Inserted 1000 tracks. Progress: 14000/113999
Inserted 1000 tracks. Progress: 15000/113999
Inserted 1000 tracks. Progress: 16000/113999
Inserted 1000 tracks. Progress: 17000/113999
Inserted 1000 tracks. Progress: 18000/113999
Inserted 1000 tracks. Progress: 19000/113999
Inserted 1000 tracks. Progress: 20000/113999
Inserted 1000 tracks. Progress: 21000/113999
Inserted 1000 tracks. Progress: 22000/113999
Inserted 1000 tracks. Progress: 23000/113999
Inserted 1000 tracks. Progress: 24000/113999
Inserted 1000 tracks. Progress: 25000/113999
Inserted 1000 tracks. Progress: 26000/113999
Inserted 1000 tracks. Progress: 27000/113999
Inserted 1000 tracks. Progress: 28000/113999
Inserted 1000 tracks. Progress: 29000/113999
Inserted 1000 tracks. Progress: 30000/113999
Inserted 1000 tracks. Progress: 31000/113999
Inserted 1000 tracks. Progress: 32000/113999
Inserted 1000 tracks. Progress: 33000/113999
Inserted 1000 tracks. Progress: 34000/113999
Inserted 1000 tracks. Progress: 35000/113999
Inserted 1000 tracks. Progress: 36000/113999
Inserted 1000 tracks. Progress: 37000/113999
Inserted 1000 tracks. Progress: 38000/113999
Inserted 1000 tracks. Progress: 39000/113999
Inserted 1000 tracks. Progress: 40000/113999
Inserted 1000 tracks. Progress: 41000/113999
Inserted 1000 tracks. Progress: 42000/113999
Inserted 1000 tracks. Progress: 43000/113999
Inserted 1000 tracks. Progress: 44000/113999
Inserted 1000 tracks. Progress: 45000/113999
Inserted 1000 tracks. Progress: 46000/113999
Inserted 1000 tracks. Progress: 47000/113999
Inserted 1000 tracks. Progress: 48000/113999
Inserted 1000 tracks. Progress: 49000/113999
Inserted 1000 tracks. Progress: 50000/113999
Inserted 1000 tracks. Progress: 51000/113999
Inserted 1000 tracks. Progress: 52000/113999
Inserted 1000 tracks. Progress: 53000/113999
Inserted 1000 tracks. Progress: 54000/113999
Inserted 1000 tracks. Progress: 55000/113999
Inserted 1000 tracks. Progress: 56000/113999
Inserted 1000 tracks. Progress: 57000/113999
Inserted 1000 tracks. Progress: 58000/113999
Inserted 1000 tracks. Progress: 59000/113999
Inserted 1000 tracks. Progress: 60000/113999
Inserted 1000 tracks. Progress: 61000/113999
Inserted 1000 tracks. Progress: 62000/113999
Inserted 1000 tracks. Progress: 63000/113999
Inserted 1000 tracks. Progress: 64000/113999
Inserted 1000 tracks. Progress: 65000/113999
Inserted 1000 tracks. Progress: 66000/113999
Inserted 1000 tracks. Progress: 67000/113999
Inserted 1000 tracks. Progress: 68000/113999
Inserted 1000 tracks. Progress: 69000/113999
Inserted 1000 tracks. Progress: 70000/113999
Inserted 1000 tracks. Progress: 71000/113999
Inserted 1000 tracks. Progress: 72000/113999
Inserted 1000 tracks. Progress: 73000/113999
Inserted 1000 tracks. Progress: 74000/113999
Inserted 1000 tracks. Progress: 75000/113999
Inserted 1000 tracks. Progress: 76000/113999
Inserted 1000 tracks. Progress: 77000/113999
Inserted 1000 tracks. Progress: 78000/113999
Inserted 1000 tracks. Progress: 79000/113999
Inserted 1000 tracks. Progress: 80000/113999
Inserted 1000 tracks. Progress: 81000/113999
Inserted 1000 tracks. Progress: 82000/113999
Inserted 1000 tracks. Progress: 83000/113999
Inserted 1000 tracks. Progress: 84000/113999
Inserted 1000 tracks. Progress: 85000/113999
Inserted 1000 tracks. Progress: 86000/113999
Inserted 1000 tracks. Progress: 87000/113999
Inserted 1000 tracks. Progress: 88000/113999
Inserted 1000 tracks. Progress: 89000/113999
Inserted 1000 tracks. Progress: 90000/113999
Inserted 1000 tracks. Progress: 91000/113999
Inserted 1000 tracks. Progress: 92000/113999
Inserted 1000 tracks. Progress: 93000/113999
Inserted 1000 tracks. Progress: 94000/113999
Inserted 1000 tracks. Progress: 95000/113999
Inserted 1000 tracks. Progress: 96000/113999
Inserted 1000 tracks. Progress: 97000/113999
Inserted 1000 tracks. Progress: 98000/113999
Inserted 1000 tracks. Progress: 99000/113999
Inserted 1000 tracks. Progress: 100000/113999
Inserted 1000 tracks. Progress: 101000/113999
Inserted 1000 tracks. Progress: 102000/113999
Inserted 1000 tracks. Progress: 103000/113999
Inserted 1000 tracks. Progress: 104000/113999
Inserted 1000 tracks. Progress: 105000/113999
Inserted 1000 tracks. Progress: 106000/113999
Inserted 1000 tracks. Progress: 107000/113999
Inserted 1000 tracks. Progress: 108000/113999
Inserted 1000 tracks. Progress: 109000/113999
Inserted 1000 tracks. Progress: 110000/113999
Inserted 1000 tracks. Progress: 111000/113999
Inserted 1000 tracks. Progress: 112000/113999
Inserted 999 tracks. Progress: 113000/113999

# Query Testing

- first 10 artists
- first 10 genres

In [ ]:
# Query the first 10 rows of the artists collection
results = artists.find().limit(10)

# Iterate through the results and print information about each artist
print("Artists:")
for artist in results:
  print(artist)

print('Genres:')
for genre in genres.find().limit(10):
  print(genre)

print('Tracks:')
for track in tracks.find().limit(10):
  print(track)

Artists:
{'_id': ObjectId('67e20950ed477bfd55a0ad6f'), 'artist': 'Gen Hoshino', 'tracks': [DBRef('tracks', '5SuOikwiRyPMVoIQDJUgSV'), DBRef('tracks', '4nmjL1mUKOAfAbo9QG9tSE'), DBRef('tracks', '12qmPGMrOCogibc7qyxT9s'), DBRef('tracks', '3dPpQeLTWjCjEbSevDMQfW'), DBRef('tracks', '2pcuXnZhTirLXsfXGVFTv2'), DBRef('tracks', '7rIBp3U5Igzn44l7Z7mOtE'), DBRef('tracks', '6hDBkm6B8HF9B4oATW28YN'), DBRef('tracks', '5SuOikwiRyPMVoIQDJUgSV'), DBRef('tracks', '5SuOikwiRyPMVoIQDJUgSV'), DBRef('tracks', '5SuOikwiRyPMVoIQDJUgSV')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad70'), 'artist': 'Ben Woodward', 'tracks': [DBRef('tracks', '4qPNDBW1i3p13qLCt0Ki3A'), DBRef('tracks', '1pG5nd6gmfbMwUfT5shDQe'), DBRef('tracks', '7bhHLZxkRekrNPPkEdDTbn'), DBRef('tracks', '14BMBNRzv24eG6OKoIgPfP'), DBRef('tracks', '0Pi3Ua6fJV1Yx5MGXhfybT'), DBRef('tracks', '1wSZdWFZphxDh6iJhWlIUi'), DBRef('tracks', '4uCVtXasfPk1Z0JwrwTIzH'), DBRef('tracks', '2wdfI1pjsfvviE7WTKGSYM'), DBRef('tracks', '1m3Lsbhkn6yL8apzsCiukd'), DBRef('tracks', '4qPNDBW1i3p13qLCt0Ki3A'), DBRef('tracks', '1pG5nd6gmfbMwUfT5shDQe'), DBRef('tracks', '7bhHLZxkRekrNPPkEdDTbn'), DBRef('tracks', '14BMBNRzv24eG6OKoIgPfP')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad71'), 'artist': 'Ingrid Michaelson', 'tracks': [DBRef('tracks', '1iJBSr7s7jYXzM8EGcbK5b'), DBRef('tracks', '0Zf1BPkkFAWGtVHeBwHHz4'), DBRef('tracks', '7aohwSiTDju51QmC54AUba'), DBRef('tracks', '4NxUuupOGPquDhy1yFIZK3'), DBRef('tracks', '3SBzDgdTwHOMSik82ZI6L2'), DBRef('tracks', '3wpZTp7HM8Dv25oExNgCC6'), DBRef('tracks', '4uBwFIBwZcgHNvwNjOqICX'), DBRef('tracks', '3tInTDUq8wdIMw5ftohmqJ'), DBRef('tracks', '6wXpQl6LNBzDhalmed8Lm5'), DBRef('tracks', '4eZP0Tyh1p06Nk1aHOzNrt'), DBRef('tracks', '0D1Kp0dQ6ZSbeI5n14XHTp'), DBRef('tracks', '0dyzpT98cEvBHybx9f04Ll')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad72'), 'artist': 'ZAYN', 'tracks': [DBRef('tracks', '1iJBSr7s7jYXzM8EGcbK5b'), DBRef('tracks', '55n9yjI6qqXh5F2mYvUc2y'), DBRef('tracks', '0PDUDa38GO8lMxLCRc4lL1'), DBRef('tracks', '2cEmWBBlCfR9wWrY9JmTyt'), DBRef('tracks', '3KPBh2wNoigGDMWQMeE7IV'), DBRef('tracks', '0B2RttXEiyXsMeQ7mMP3EI'), DBRef('tracks', '1iQDltZqI7BXnHrFy4Qo1k'), DBRef('tracks', '2ez6qvOTHKeI3ss80NGqnI'), DBRef('tracks', '0B2RttXEiyXsMeQ7mMP3EI'), DBRef('tracks', '0B2RttXEiyXsMeQ7mMP3EI'), DBRef('tracks', '3e7sxremeOE3wTySiOhGiP'), DBRef('tracks', '55n9yjI6qqXh5F2mYvUc2y')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad73'), 'artist': 'Kina Grannis', 'tracks': [DBRef('tracks', '6lfxq3CG4xtTiEg7opyCyx'), DBRef('tracks', '65VhbQdqvozUntjnlFkFbZ'), DBRef('tracks', '34dnNAUoIPcwnK0RtVMBWZ'), DBRef('tracks', '5oV8bZaShr2d01FFMHBUPq'), DBRef('tracks', '7BRwh1bemr9rFMDeTbcy5S'), DBRef('tracks', '1RZkqIEM5aV000fKgz9J46'), DBRef('tracks', '1uxm47Qn1JhUWZHQfcY6w1'), DBRef('tracks', '24UxG3p1Ghtc5ejJtGBoeL'), DBRef('tracks', '38ssTLOvoZyL4CLa4ImDG9'), DBRef('tracks', '0c99BUd87HQfzgUUQqRyds'), DBRef('tracks', '3YvutLE6lwEyW4WMF5FIi6'), DBRef('tracks', '5Z8O4RFAmjA13jrOYIgyXA'), DBRef('tracks', '63wsZUhUZLlh1OsyrZq7sz'), DBRef('tracks', '1wflx5YklLYToaIbXkrZSq'), DBRef('tracks', '1YnLthg0HOs8YTzgN5hVh2'), DBRef('tracks', '4XlevPQOF6GkZCS2yWOkNn'), DBRef('tracks', '14UvqLsdqw2dsmVkmTYptE'), DBRef('tracks', '0F78T5bfHQCliaNjBkIYBq'), DBRef('tracks', '2R6CGc2eQJjuVEbH1eUZjq'), DBRef('tracks', '0W85Yolr3l72QZsk9UrkqP'), DBRef('tracks', '77enz5hl8RicxrbPB56VXQ'), DBRef('tracks', '3YvutLE6lwEyW4WMF5FIi6')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad74'), 'artist': 'Chord Overstreet', 'tracks': [DBRef('tracks', '5vjLSffimiIP26QG5WcN2K'), DBRef('tracks', '4LbWtBkN82ZRhz9jqzgrb3'), DBRef('tracks', '1m5LC29RE52Bxy7hxvpOlL'), DBRef('tracks', '25UzeaV47eDT44Fovve6xQ'), DBRef('tracks', '2gRKq9rIC5i1zuxp06zJWH'), DBRef('tracks', '00DuOxungwHwVUX2m37P0P'), DBRef('tracks', '4bXoVtbp6fN8FaSQvGQB41'), DBRef('tracks', '5xQTEPjGsLuvwnnvyK3fAA'), DBRef('tracks', '2Jhx81CSHw8xWwBqRM2mZR'), DBRef('tracks', '6IiFTtc2ipIXW5HzwFzOjh'), DBRef('tracks', '7AWKPOhCIHxetMXujii1KT'), DBRef('tracks', '7qHPp1beQupJUzwRyVtoyy')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad75'), 'artist': 'Tyrone Wells', 'tracks': [DBRef('tracks', '01MVOl9KtVTNfFiBU9I7dc'), DBRef('tracks', '4UU97IGHOhBhZjCUgDFUiz'), DBRef('tracks', '1z2fSrYZqrO5tMqzULn9OD'), DBRef('tracks', '01MVOl9KtVTNfFiBU9I7dc')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad76'), 'artist': 'A Great Big World', 'tracks': [DBRef('tracks', '6Vc5wAMmXdKIAM7WUoEb7N'), DBRef('tracks', '5TvE3pk05pyFIGdSY9j4DJ'), DBRef('tracks', '2SkJKMfjpYsNv0KWOxiegX'), DBRef('tracks', '78TKtlSLWK8pZAKKW3MyQL'), DBRef('tracks', '7xLhousIHDxoGgeJNhO4Ye'), DBRef('tracks', '6kRZfOZSuoi0Htg6gROKDz'), DBRef('tracks', '2fPb58e6f8KxejYDCaARwS'), DBRef('tracks', '71vcffc4Yfz0pt9AbaL386'), DBRef('tracks', '7oyFihJppZYPP7o0NfoHnZ'), DBRef('tracks', '1o0yFkUycTAWIIWFOlhDcV'), DBRef('tracks', '1qHiDbTJI7GB62W3BBFigx'), DBRef('tracks', '4eZP0Tyh1p06Nk1aHOzNrt'), DBRef('tracks', '0jJqIi0uMG8IhGlLx7U85J'), DBRef('tracks', '6Vc5wAMmXdKIAM7WUoEb7N'), DBRef('tracks', '5TvE3pk05pyFIGdSY9j4DJ'), DBRef('tracks', '2SkJKMfjpYsNv0KWOxiegX'), DBRef('tracks', '7xLhousIHDxoGgeJNhO4Ye'), DBRef('tracks', '78TKtlSLWK8pZAKKW3MyQL'), DBRef('tracks', '6kRZfOZSuoi0Htg6gROKDz'), DBRef('tracks', '2fPb58e6f8KxejYDCaARwS'), DBRef('tracks', '71vcffc4Yfz0pt9AbaL386'), DBRef('tracks', '7oyFihJppZYPP7o0NfoHnZ'), DBRef('tracks', '1o0yFkUycTAWIIWFOlhDcV'), DBRef('tracks', '1qHiDbTJI7GB62W3BBFigx')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad77'), 'artist': 'Christina Aguilera', 'tracks': [DBRef('tracks', '6Vc5wAMmXdKIAM7WUoEb7N'), DBRef('tracks', '5TvE3pk05pyFIGdSY9j4DJ'), DBRef('tracks', '78TKtlSLWK8pZAKKW3MyQL'), DBRef('tracks', '7oyFihJppZYPP7o0NfoHnZ'), DBRef('tracks', '0N29rN62Oy0EgWD1U2DuKQ'), DBRef('tracks', '6Vc5wAMmXdKIAM7WUoEb7N'), DBRef('tracks', '5TvE3pk05pyFIGdSY9j4DJ'), DBRef('tracks', '78TKtlSLWK8pZAKKW3MyQL'), DBRef('tracks', '7oyFihJppZYPP7o0NfoHnZ'), DBRef('tracks', '0N29rN62Oy0EgWD1U2DuKQ')]}
{'_id': ObjectId('67e20950ed477bfd55a0ad78'), 'artist': 'Jason Mraz', 'tracks': [DBRef('tracks', '1EzrEOXmMH3G43AXT1y7pA'), DBRef('tracks', '0IktbUcnAGrvD03AWnz3Q8'), DBRef('tracks', '5ivF4eQBqJiVL5IAE9jRyl'), DBRef('tracks', '2qLMf6TuEC3ruGJg4SMMN6'), DBRef('tracks', '3S0OXQeoh0w6AY8WQVckRW'), DBRef('tracks', '0BUuuEvNa5T4lMaewyiudB'), DBRef('tracks', '3Hn3LfhrQOaKihdCibJsTs'), DBRef('tracks', '6D33wCKzWtNEgOovgeVJ7r'), DBRef('tracks', '5IfCZDRXZrqZSm8AwE44PG'), DBRef('tracks', '0dzKBptH2P5j5a0MifBMwM'), DBRef('tracks', '5QAMZTM5cmLg3fHX9ZbTZi'), DBRef('tracks', '2qESE1ZeWly7I3YjyTXmXh'), DBRef('tracks', '3EQV1ZHtHvq9OnVRYIdbg3'), DBRef('tracks', '3ax0rfGb7exLtl02LL08U9'), DBRef('tracks', '38jy6kRlPt8z1GUS9WXeNh'), DBRef('tracks', '7BXW1QCg56yzEBV8pW8pah'), DBRef('tracks', '05pKAafT85jeeNhZ6kq7HT'), DBRef('tracks', '2D9w6sabdMCLSheW5aegwO'), DBRef('tracks', '1Qo3taHLFSQpzLm5Sty7M4'), DBRef('tracks', '71M4QMn8nrok1KFVXwEEyU'), DBRef('tracks', '1uSuY2qLCbx1QB7oPUVhFG'), DBRef('tracks', '6twvFrIoIINH8UW8EB8OnU'), DBRef('tracks', '2pelUnMKr07JjJpilj9Yew'), DBRef('tracks', '73CbJykoV6WapWGfTeRzTl'), DBRef('tracks', '3ixLIO5BsTmic0Pp27FaPY'), DBRef('tracks', '5ZetMq21bMQN5oo4TtdOxu'), DBRef('tracks', '73oHkllHIT8fdbzpxiXW40'), DBRef('tracks', '4MihgVRpD82EZoT61GW63w'), DBRef('tracks', '1BECZPXBXzobsfmlzj0g3I'), DBRef('tracks', '14vExHBkh1prEAN94wZug8'), DBRef('tracks', '03yc0G2OoH1Eeyu7Piy8fK'), DBRef('tracks', '3dglCYsVMjPbDlU2CC9Vq7'), DBRef('tracks', '03VNgdCL9t8aPyvwZecglI'), DBRef('tracks', '4Bo6FwC7Oe9zywSZc6q7hO'), DBRef('tracks', '3IORLAm07yxo4T7B8cRET3'), DBRef('tracks', '4tK4ARuilOrBzwVQK73E0Y'), DBRef('tracks', '1pIMxRddmCGalHnRbLFkWg'), DBRef('tracks', '4Akic5cb5RHJrTdQZY7AfX'), DBRef('tracks', '6Vn8lTVMjILXQCjZUXS8n4'), DBRef('tracks', '7Igc6JB0xPDcn5yRkkVGQX'), DBRef('tracks', '2mKjs6s0Z1imKKb6gOk628'), DBRef('tracks', '26TzE0IIiuqPKLaWfcsj4C'), DBRef('tracks', '395XDt5vt8DKguJDjGtYLU'), DBRef('tracks', '28WClWvliFajAplluwtX2J'), DBRef('tracks', '6TbDpqKCksZNJjriFhPum8'), DBRef('tracks', '4ci2OgZphnEFQXY7xNlf71'), DBRef('tracks', '6D33wCKzWtNEgOovgeVJ7r'), DBRef('tracks', '3Hn3LfhrQOaKihdCibJsTs'), DBRef('tracks', '5IfCZDRXZrqZSm8AwE44PG'), DBRef('tracks', '2qESE1ZeWly7I3YjyTXmXh'), DBRef('tracks', '5QAMZTM5cmLg3fHX9ZbTZi'), DBRef('tracks', '3ax0rfGb7exLtl02LL08U9'), DBRef('tracks', '3EQV1ZHtHvq9OnVRYIdbg3'), DBRef('tracks', '0BUuuEvNa5T4lMaewyiudB'), DBRef('tracks', '0dzKBptH2P5j5a0MifBMwM'), DBRef('tracks', '1EzrEOXmMH3G43AXT1y7pA')]}
Genres:

# Random halving CV for best parameters for random forest

Do not run this. The best found parameters are implemented in the random forest below.

In [ ]:
from sklearn.experimental import enable_halving_search_cv  # Needed for HalvingRandomSearchCV
from sklearn.model_selection import HalvingRandomSearchCV
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# Fetch data from MongoDB
genre_data = list(genres.aggregate([
    {
        '$lookup': {
            'from': 'tracks',
            'localField': '_id',
            'foreignField': 'track_genre.$id',
            'as': 'tracks'
        }
    },
    {
        '$unwind': '$tracks'
    },
    {
        '$project': {
            '_id': 0,
            'genre': '$genre',
            'track_id': '$tracks.track_id',
            'popularity': '$tracks.popularity',
            'danceability': '$tracks.danceability',
            'energy': '$tracks.energy',
            'loudness': '$tracks.loudness',
            'speechiness': '$tracks.speechiness',
            'acousticness': '$tracks.acousticness',
            'instrumentalness': '$tracks.instrumentalness',
            'liveness': '$tracks.liveness',
            'valence': '$tracks.valence',
            'tempo': '$tracks.tempo',
        }
    }
]))

# Create a DataFrame from the retrieved data
df_genre_tracks = pd.DataFrame(genre_data)

# Prepare data for model training
X = df_genre_tracks[['danceability', 'energy', 'loudness', 'speechiness',
                     'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']]
y = df_genre_tracks['genre']

# Encode genre labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Define the parameter distributions to sample from
param_dist = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# Create a HalvingRandomSearchCV object

search = HalvingRandomSearchCV(
    estimator=RandomForestClassifier(),
    param_distributions=param_dist,
    n_candidates='exhaust',  # Explore all candidates initially
    factor=3,  # Each iteration reduces candidates by this factor
    resource='n_samples',  # Resource used to control iterations (samples here)
    max_resources=len(X_train),  # Maximum resource value
    scoring='accuracy',
    random_state=42,
    cv=5,  # Cross-validation folds
    verbose=2  # Increased verbosity for monitoring
)

# Fit the model
search.fit(X_train, y_train)

# Get the best parameters
best_params = search.best_params_
print("Best parameters:", best_params)

# Use the best model
best_model = search.best_estimator_

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


# Function to predict the genre of a track
def predict_track_genre(track_features):

    input_features = pd.DataFrame([track_features])
    prediction = model.predict(input_features)[0]
    predicted_genre = le.inverse_transform([prediction])[0]
    return predicted_genre

n_iterations: 4
n_required_iterations: 4
n_possible_iterations: 4
min_resources_: 1140
max_resources_: 91199
aggressive_elimination: False
factor: 3
----------
iter: 0
n_candidates: 79
n_resources: 1140
Fitting 5 folds for each of 79 candidates, totalling 395 fits
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=300; total time=   2.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=300; total time=   2.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=300; total time=   2.3s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=300; total time=   2.2s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=300; total time=   2.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   1.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   1.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   1.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   1.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   1.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   1.8s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   1.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   1.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   1.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   1.5s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   2.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   3.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   2.2s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.7s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   2.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   2.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   2.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   2.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   2.1s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   1.1s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   1.1s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.9s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.1s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   3.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   2.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   2.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   2.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   3.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   2.9s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   1.9s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   1.9s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   1.9s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   2.2s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   2.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   3.4s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.6s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.1s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.3s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.3s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.0s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.4s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   1.6s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.6s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   1.9s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   2.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   1.9s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   1.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.0s

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
125 fits failed out of a total of 395.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
125 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.09130536 0.09481413 0.08778886        nan
 0.08954711 0.09656851        nan 0.09393693 0.0895587  0.09481026
 0.09480253        nan        nan 0.09656851 0.0833913         nan
 0.08603061 0.09481026 0.09306361        nan 0.09216323 0.09831517
        nan        nan        nan 0.09042816        nan 0.09042816
 0.09832676 0.10095834        nan 0.08866605        nan 0.0895587
        nan 0.09657238 0.09393693 0.09218641 0.10007342 0.09217482
 0.09128603        nan 0.08953938 0.08954324        nan 0.09217868
        nan 0.09218255 0.09481026 0.09130922 0.09304428        nan
 0.09305588        nan        nan        nan 0.09919236 0.09920396
 0.08691939        nan 0.09394466 0.09041657 0.09656465 0.09306361
 0.08779272 0.09217868 0.10096221        nan 0.09744184 0.09744957
 0.09043203 0.09043203 0.08691166 0.08603061 0.08778113        nan
 0.09217868]
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the train scores are non-finite: [       nan        nan 0.8678645  0.96839313 0.96817263        nan
 0.95390596 0.82264983        nan 0.95676262 0.96509884 0.96992942
 0.99473203        nan        nan 0.87532425 0.96905054        nan
 0.9931955  0.90386023 0.97497809        nan 0.95588543 0.99495181
        nan        nan        nan 0.96729423        nan 0.90737261
 0.91769551 0.99626856        nan 0.97388088        nan 0.87993626
        nan 0.97651366 0.97344204 0.93985812 0.9629049  0.94205688
 0.94512778        nan 0.97234387 0.99363457        nan 0.99473227
        nan 0.86194393 0.96575866 0.90715355 0.838674          nan
 0.99626856        nan        nan        nan 0.97761088 0.99341528
 0.90407928        nan 0.82199097 0.99451249 0.99341503 0.96488195
 0.96290562 0.8790593  0.99517111        nan 0.97322082 0.99626856
 0.94644116 0.99626856 0.92735042 0.82923792 0.94688168        nan
 0.99626856]
  warnings.warn(

[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   3.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   3.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   3.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   4.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   3.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   2.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   2.0s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   2.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   2.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   2.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   2.3s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.9s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.3s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   7.0s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.3s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   3.1s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   2.6s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   2.6s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   2.5s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   2.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   5.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   5.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   5.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   5.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   5.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   5.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   5.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   5.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   5.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   5.6s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   5.2s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   6.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   5.2s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   6.0s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   5.3s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   2.3s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.8s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   8.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   7.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   8.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   8.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   7.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   2.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   2.1s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   2.0s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   2.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   3.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   3.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   3.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   4.0s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   6.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   6.9s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   6.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   6.9s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=   6.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   5.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   4.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   5.0s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   4.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   4.6s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.3s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.2s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   7.6s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.2s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.4s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   5.5s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   4.8s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   5.5s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   4.8s
[CV] END max_depth=10, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=300; total time=   5.1s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   5.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   4.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   5.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   4.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   5.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   5.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   5.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   2.8s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   2.7s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   2.8s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   3.5s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   2.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   7.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   7.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   7.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   7.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   8.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   7.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.0s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   7.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=   8.1s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=100; total time=   2.1s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=100; total time=   2.1s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=100; total time=   2.6s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=100; total time=   2.3s
[CV] END max_depth=None, max_features=log2, min_samples_leaf=4, min_samples_split=5, n_estimators=100; total time=   2.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   5.8s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   5.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   5.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   8.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   8.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   8.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   8.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   8.8s
----------
iter: 2
n_candidates: 9
n_resources: 10260
Fitting 5 folds for each of 9 candidates, totalling 45 fits

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.09130536 0.09481413 0.08778886        nan
 0.08954711 0.09656851        nan 0.09393693 0.0895587  0.09481026
 0.09480253        nan        nan 0.09656851 0.0833913         nan
 0.08603061 0.09481026 0.09306361        nan 0.09216323 0.09831517
        nan        nan        nan 0.09042816        nan 0.09042816
 0.09832676 0.10095834        nan 0.08866605        nan 0.0895587
        nan 0.09657238 0.09393693 0.09218641 0.10007342 0.09217482
 0.09128603        nan 0.08953938 0.08954324        nan 0.09217868
        nan 0.09218255 0.09481026 0.09130922 0.09304428        nan
 0.09305588        nan        nan        nan 0.09919236 0.09920396
 0.08691939        nan 0.09394466 0.09041657 0.09656465 0.09306361
 0.08779272 0.09217868 0.10096221        nan 0.09744184 0.09744957
 0.09043203 0.09043203 0.08691166 0.08603061 0.08778113        nan
 0.09217868 0.14039283 0.14595096 0.13834605 0.13951821 0.14302484
 0.1471214  0.13922495 0.14507162 0.13717432 0.14799988 0.14682943
 0.14009958 0.14975341 0.14682686 0.14360963 0.14127045 0.14565599
 0.14887579 0.14448854 0.14010386 0.14010043 0.1368862  0.14946058
 0.14712312 0.14507205 0.14127088 0.14390588]
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the train scores are non-finite: [       nan        nan 0.8678645  0.96839313 0.96817263        nan
 0.95390596 0.82264983        nan 0.95676262 0.96509884 0.96992942
 0.99473203        nan        nan 0.87532425 0.96905054        nan
 0.9931955  0.90386023 0.97497809        nan 0.95588543 0.99495181
        nan        nan        nan 0.96729423        nan 0.90737261
 0.91769551 0.99626856        nan 0.97388088        nan 0.87993626
        nan 0.97651366 0.97344204 0.93985812 0.9629049  0.94205688
 0.94512778        nan 0.97234387 0.99363457        nan 0.99473227
        nan 0.86194393 0.96575866 0.90715355 0.838674          nan
 0.99626856        nan        nan        nan 0.97761088 0.99341528
 0.90407928        nan 0.82199097 0.99451249 0.99341503 0.96488195
 0.96290562 0.8790593  0.99517111        nan 0.97322082 0.99626856
 0.94644116 0.99626856 0.92735042 0.82923792 0.94688168        nan
 0.99626856 0.67987601 0.92285732 0.67775575 0.98376701 0.96183091
 0.80688789 0.78173509 0.82940962 0.6648135  0.98318203 0.94589042
 0.72155644 0.95174019 0.94918102 0.9820853  0.66430231 0.6939153
 0.96175778 0.82414411 0.98376701 0.98325516 0.74985367 0.96351241
 0.98106164 0.94603676 0.98376701 0.98340138]
  warnings.warn(

[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   6.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   6.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   6.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   6.4s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=100; total time=   6.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=  14.0s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=  13.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=  13.9s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=  14.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=  14.1s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   6.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   6.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   6.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   6.9s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   6.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  13.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  13.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  13.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  13.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  13.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=  22.8s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=  21.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=  22.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=  22.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300; total time=  22.7s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  22.8s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  22.6s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  22.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  22.3s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=  22.1s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  14.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  14.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  14.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  14.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  15.1s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=  21.5s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=  22.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=  22.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=  22.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=  22.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  18.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  19.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  19.0s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  19.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  19.9s
----------
iter: 3
n_candidates: 3
n_resources: 30780
Fitting 5 folds for each of 3 candidates, totalling 15 fits

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.09130536 0.09481413 0.08778886        nan
 0.08954711 0.09656851        nan 0.09393693 0.0895587  0.09481026
 0.09480253        nan        nan 0.09656851 0.0833913         nan
 0.08603061 0.09481026 0.09306361        nan 0.09216323 0.09831517
        nan        nan        nan 0.09042816        nan 0.09042816
 0.09832676 0.10095834        nan 0.08866605        nan 0.0895587
        nan 0.09657238 0.09393693 0.09218641 0.10007342 0.09217482
 0.09128603        nan 0.08953938 0.08954324        nan 0.09217868
        nan 0.09218255 0.09481026 0.09130922 0.09304428        nan
 0.09305588        nan        nan        nan 0.09919236 0.09920396
 0.08691939        nan 0.09394466 0.09041657 0.09656465 0.09306361
 0.08779272 0.09217868 0.10096221        nan 0.09744184 0.09744957
 0.09043203 0.09043203 0.08691166 0.08603061 0.08778113        nan
 0.09217868 0.14039283 0.14595096 0.13834605 0.13951821 0.14302484
 0.1471214  0.13922495 0.14507162 0.13717432 0.14799988 0.14682943
 0.14009958 0.14975341 0.14682686 0.14360963 0.14127045 0.14565599
 0.14887579 0.14448854 0.14010386 0.14010043 0.1368862  0.14946058
 0.14712312 0.14507205 0.14127088 0.14390588 0.17915946 0.18208372
 0.17935405 0.1707763  0.18208367 0.18130451 0.18354604 0.18432581
 0.18588527]
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the train scores are non-finite: [       nan        nan 0.8678645  0.96839313 0.96817263        nan
 0.95390596 0.82264983        nan 0.95676262 0.96509884 0.96992942
 0.99473203        nan        nan 0.87532425 0.96905054        nan
 0.9931955  0.90386023 0.97497809        nan 0.95588543 0.99495181
        nan        nan        nan 0.96729423        nan 0.90737261
 0.91769551 0.99626856        nan 0.97388088        nan 0.87993626
        nan 0.97651366 0.97344204 0.93985812 0.9629049  0.94205688
 0.94512778        nan 0.97234387 0.99363457        nan 0.99473227
        nan 0.86194393 0.96575866 0.90715355 0.838674          nan
 0.99626856        nan        nan        nan 0.97761088 0.99341528
 0.90407928        nan 0.82199097 0.99451249 0.99341503 0.96488195
 0.96290562 0.8790593  0.99517111        nan 0.97322082 0.99626856
 0.94644116 0.99626856 0.92735042 0.82923792 0.94688168        nan
 0.99626856 0.67987601 0.92285732 0.67775575 0.98376701 0.96183091
 0.80688789 0.78173509 0.82940962 0.6648135  0.98318203 0.94589042
 0.72155644 0.95174019 0.94918102 0.9820853  0.66430231 0.6939153
 0.96175778 0.82414411 0.98376701 0.98325516 0.74985367 0.96351241
 0.98106164 0.94603676 0.98376701 0.98340138 0.89867441 0.92784389
 0.92165415 0.51613259 0.96105863 0.96271569 0.93866367 0.94144167
 0.92796577]
  warnings.warn(

[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  42.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  42.9s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  42.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  42.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=  42.2s
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time= 1.1min
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time= 1.1min
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time= 1.1min
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time= 1.1min
[CV] END max_depth=20, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time= 1.1min
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  57.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  58.0s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  57.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  57.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_leaf=4, min_samples_split=2, n_estimators=300; total time=  56.8s

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.09130536 0.09481413 0.08778886        nan
 0.08954711 0.09656851        nan 0.09393693 0.0895587  0.09481026
 0.09480253        nan        nan 0.09656851 0.0833913         nan
 0.08603061 0.09481026 0.09306361        nan 0.09216323 0.09831517
        nan        nan        nan 0.09042816        nan 0.09042816
 0.09832676 0.10095834        nan 0.08866605        nan 0.0895587
        nan 0.09657238 0.09393693 0.09218641 0.10007342 0.09217482
 0.09128603        nan 0.08953938 0.08954324        nan 0.09217868
        nan 0.09218255 0.09481026 0.09130922 0.09304428        nan
 0.09305588        nan        nan        nan 0.09919236 0.09920396
 0.08691939        nan 0.09394466 0.09041657 0.09656465 0.09306361
 0.08779272 0.09217868 0.10096221        nan 0.09744184 0.09744957
 0.09043203 0.09043203 0.08691166 0.08603061 0.08778113        nan
 0.09217868 0.14039283 0.14595096 0.13834605 0.13951821 0.14302484
 0.1471214  0.13922495 0.14507162 0.13717432 0.14799988 0.14682943
 0.14009958 0.14975341 0.14682686 0.14360963 0.14127045 0.14565599
 0.14887579 0.14448854 0.14010386 0.14010043 0.1368862  0.14946058
 0.14712312 0.14507205 0.14127088 0.14390588 0.17915946 0.18208372
 0.17935405 0.1707763  0.18208367 0.18130451 0.18354604 0.18432581
 0.18588527 0.21498418 0.21511424 0.21322971]
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the train scores are non-finite: [       nan        nan 0.8678645  0.96839313 0.96817263        nan
 0.95390596 0.82264983        nan 0.95676262 0.96509884 0.96992942
 0.99473203        nan        nan 0.87532425 0.96905054        nan
 0.9931955  0.90386023 0.97497809        nan 0.95588543 0.99495181
        nan        nan        nan 0.96729423        nan 0.90737261
 0.91769551 0.99626856        nan 0.97388088        nan 0.87993626
        nan 0.97651366 0.97344204 0.93985812 0.9629049  0.94205688
 0.94512778        nan 0.97234387 0.99363457        nan 0.99473227
        nan 0.86194393 0.96575866 0.90715355 0.838674          nan
 0.99626856        nan        nan        nan 0.97761088 0.99341528
 0.90407928        nan 0.82199097 0.99451249 0.99341503 0.96488195
 0.96290562 0.8790593  0.99517111        nan 0.97322082 0.99626856
 0.94644116 0.99626856 0.92735042 0.82923792 0.94688168        nan
 0.99626856 0.67987601 0.92285732 0.67775575 0.98376701 0.96183091
 0.80688789 0.78173509 0.82940962 0.6648135  0.98318203 0.94589042
 0.72155644 0.95174019 0.94918102 0.9820853  0.66430231 0.6939153
 0.96175778 0.82414411 0.98376701 0.98325516 0.74985367 0.96351241
 0.98106164 0.94603676 0.98376701 0.98340138 0.89867441 0.92784389
 0.92165415 0.51613259 0.96105863 0.96271569 0.93866367 0.94144167
 0.92796577 0.88520581 0.88730952 0.87591378]
  warnings.warn(

Best parameters: {'n_estimators': 300, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 20}

declare the prediction method with the resultant random forest from the CV

In [ ]:
# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


# Function to predict the genre of a track
def predict_track_genre(track_features):

    input_features = pd.DataFrame([track_features])
    prediction = best_model.predict(input_features)[0]
    predicted_genre = le.inverse_transform([prediction])[0]
    return predicted_genre

Accuracy: 0.23258771929824562

create a random forest without the CV (use this one)

In [ ]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Fetch data from MongoDB
genre_data = list(genres.aggregate([
    {
        '$lookup': {
            'from': 'tracks',
            'localField': '_id',
            'foreignField': 'track_genre.$id',
            'as': 'tracks'
        }
    },
    {
        '$unwind': '$tracks'
    },
    {
        '$project': {
            '_id': 0,
            'genre': '$genre',
            'track_id': '$tracks.track_id',
            'popularity': '$tracks.popularity',
            'danceability': '$tracks.danceability',
            'energy': '$tracks.energy',
            'loudness': '$tracks.loudness',
            'speechiness': '$tracks.speechiness',
            'acousticness': '$tracks.acousticness',
            'instrumentalness': '$tracks.instrumentalness',
            'liveness': '$tracks.liveness',
            'valence': '$tracks.valence',
            'tempo': '$tracks.tempo',
        }
    }
]))

# Create a DataFrame from the retrieved data
df_genre_tracks = pd.DataFrame(genre_data)

# Prepare data for model training
X = df_genre_tracks[['danceability', 'energy', 'loudness', 'speechiness',
                     'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']]
y = df_genre_tracks['genre']

# Encode genre labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Train a Random Forest classifier
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=10,
    min_samples_leaf=1,
    max_features='log2',
    random_state=42
)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


# Function to predict the genre of a track
def predict_track_genre(track_features):

    input_features = pd.DataFrame([track_features])
    prediction = model.predict(input_features)[0]
    predicted_genre = le.inverse_transform([prediction])[0]
    return predicted_genre


track_features = {

    'danceability': 0.7,
    'energy': 0.8,
    'loudness': -5,
    'speechiness': 0.1,
    'acousticness': 0.2,
    'instrumentalness': 0.0,
    'liveness': 0.3,
    'valence': 0.9,
    'tempo': 120,
}

predicted_genre = predict_track_genre(track_features)
print("Predicted Genre:", predicted_genre)

Accuracy: 0.23105263157894737
Predicted Genre: party

prediction tersting area

In [ ]:
humble = {
    'danceability': 0.539,
    'energy': 0.362,
    'loudness': -13.618,
    'speechiness': 0.0313,
    'acousticness': 0.945,
    'instrumentalness': 0.724,
    'liveness': 0.269,
    'valence': 0.587,
    'tempo': 96.286,
}

print(predict_track_genre(humble))

tango

In [ ]:
def get_track_info(track):
  if track:
    print("Song Name:", track['track_name'])

    artist_ref = track['artists'][0]
    artist = artists.find_one({'_id': artist_ref.id})
    if artist:
      print("Artist Name:", artist['artist'])
    else:
      print("Artist not found.")

    track_features = {
        'danceability': track['danceability'],
        'energy': track['energy'],
        'loudness': track['loudness'],
        'speechiness': track['speechiness'],
        'acousticness': track['acousticness'],
        'instrumentalness': track['instrumentalness'],
        'liveness': track['liveness'],
        'valence': track['valence'],
        'tempo': track['tempo'],
    }

    predicted_genre = predict_track_genre(track_features)
    print("Predicted Genre:", predicted_genre)

    genre_ref = track['track_genre']
    genre = genres.find_one({'_id': genre_ref.id})
    if genre:
      print("Actual Genre:", genre['genre'])
    else:
      print("Genre not found.")

  else:
    print("Track not found.")


song_name = input("Enter the song name: ")
track2 = tracks.find_one({'track_name': song_name})
if track2:
  get_track_info(track2)
else:
  print("Track not found.")

Enter the song name: Higher
Song Name: Higher
Artist Name: Jor'dan Armstrong
Predicted Genre: afrobeat
Actual Genre: afrobeat

In [ ]:
def recommend_tracks(track_name, num_recommendations=5):


  # Find the track in the database based on the track name
  input_track = tracks.find_one({'track_name': track_name})

  if not input_track:
    print(f"Track '{track_name}' not found in the database.")
    return []

  # Extract the track's features
  input_track_features = {
      'danceability': input_track['danceability'],
      'energy': input_track['energy'],
      'loudness': input_track['loudness'],
      'speechiness': input_track['speechiness'],
      'acousticness': input_track['acousticness'],
      'instrumentalness': input_track['instrumentalness'],
      'liveness': input_track['liveness'],
      'valence': input_track['valence'],
      'tempo': input_track['tempo'],
  }

  # Predict the genre of the input track
  predicted_genre = predict_track_genre(input_track_features)

  # Find tracks with similar features and genre
  similar_tracks = list(tracks.find({
      'track_genre.$id': input_track['track_genre'].id,
      'track_name': {'$ne': track_name}  # Exclude the input track itself
  }))


  # Sort tracks by similarity (e.g., Euclidean distance of features)
  def calculate_similarity(track):
    track_features = {
        'danceability': track['danceability'],
        'energy': track['energy'],
        'loudness': track['loudness'],
        'speechiness': track['speechiness'],
        'acousticness': track['acousticness'],
        'instrumentalness': track['instrumentalness'],
        'liveness': track['liveness'],
        'valence': track['valence'],
        'tempo': track['tempo'],
    }
    similarity = 0
    for feature in input_track_features:
      similarity += abs(input_track_features[feature] - track_features[feature])
    return similarity

  similar_tracks.sort(key=calculate_similarity)

  return_list = []

  for track in similar_tracks[:num_recommendations]:
    track_artist_ref = track['artists'][0]
    artist = artists.find_one({'_id': track_artist_ref.id})
    if artist:
      return_list.append(track['track_name'] + ' - ' + artist['artist'])
    else:
      print("Artist not found.")

  return return_list

song_name = input("Enter the song name: ")
recommendations = recommend_tracks(song_name)

if recommendations:
    print("Recommended tracks:")
    for track_name in recommendations:
        print("- ", track_name)
else:
    print("No recommendations found.")

Enter the song name: Man in the Box
Recommended tracks:
-  One Headlight - The Wallflowers
-  One Headlight - The Wallflowers
-  El Arte del Buen Comer - Patricio Rey y sus Redonditos de Ricota
-  Passion - RAC
-  A Change Of Heart - The 1975

In [ ]:
!pip install supertree

import matplotlib.pyplot as plt
from supertree import SuperTree

# Create the SuperTree visualization
st = SuperTree(model, X_train, y_train)
st.show_tree(which_tree=0)

Requirement already satisfied: supertree in /usr/local/lib/python3.11/dist-packages (0.5.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from supertree) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from supertree) (2.0.2)
Requirement already satisfied: ipython in /usr/local/lib/python3.11/dist-packages (from supertree) (7.34.0)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.11/dist-packages (from supertree) (7.7.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (75.1.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (3.0.50)
Requirement already satisfied: pygments in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython->supertree) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->supertree) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->supertree) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->supertree) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->supertree) (3.0.13)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->supertree) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->supertree) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->supertree) (2025.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (1.8.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (6.1.12)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (24.0.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->supertree) (6.4.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi>=0.16->ipython->supertree) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.11/dist-packages (from pexpect>4.3->ipython->supertree) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->supertree) (0.2.13)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->supertree) (1.17.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.11/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->supertree) (6.5.7)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->supertree) (5.7.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (3.1.6)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (23.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (7.16.6)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.21.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.2.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from jupyter-core>=4.6.0->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->supertree) (4.3.7)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.11/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (4.13.3)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.11/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.11/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (4.23.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.11/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (21.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (0.23.1)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.11/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.16.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (4.12.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (2.22)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (4.9.0)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.8.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->supertree) (1.3.1)